name: Build Linux
run-name: Build Linux (Triggered by ${{ github.event_name }} by @${{ github.actor }})
on: 
  workflow_call:
    inputs:
      OS:
        description: 'Operating system'
        required: true
        type: string
      COVERITY_OPTS:
        description: 'COVERITY_OPTS'
        required: false
        default: ''
        type: string

jobs:
  scan:
    runs-on: [self-hosted, "${{ inputs.OS }}", "${{ inputs.OS == 'Windows' && 'Coverity' || 'docker' }}"]
    steps:
      - name: Cleanup workspace (Linux)
        if: always() && runner.os == 'Linux'
        run: sudo rm -rf ..?* .[!.]* *
      - name: Cleanup workspace (Windows)
        if: always() && runner.os == 'Windows'
        run: Remove-Item -Recurse -Force .\*

      - name: Checkout dispatcher source
        uses: actions/checkout@v3
        with:
          path: source

      - name: Write Docker File (Linux)
        if: success() && runner.os == 'Linux'
        run: |
          USER_ID=$(id -u ${USER})
          GROUP_ID=$(id -g ${USER})
          # Dockerfile will contain everything between <<EOL and EOL
          cat >Dockerfile <<EOL
          FROM public.ecr.aws/docker/library/centos:7 AS buildenv

          ARG http_proxy
          ARG https_proxy
          ARG no_proxy
          ENV http_proxy \${http_proxy}
          ENV https_proxy \${https_proxy}
          ENV no_proxy \${no_proxy}

          # basic build tools
          RUN yum install -y \
              centos-release-scl \
              && yum-config-manager --enable rhel-server-rhscl-7-rpms \
              && yum install -y \
              devtoolset-9

          # cmake
          RUN yum install -y \
              openssl-devel \
              && cd /tmp \
              && curl -O -L --retry 5 \
              https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4.tar.gz \
              && tar zxvf cmake-3.* \
              && cd cmake-3.* \
              && source /opt/rh/devtoolset-9/enable \
              && ./bootstrap --prefix=/usr/local --parallel=\$(nproc) \
              && make -j\$(nproc) \
              && make install

          #install xcb and wayland
          RUN yum -y update \
              && yum -y install wayland-devel libX11-devel libXext-devel libXfixes-devel libpciaccess-devel \
              && cd /tmp \
              && curl -O -L --retry 5 \
              https://wayland.freedesktop.org/releases/wayland-protocols-1.15.tar.xz \
              && tar -xJf wayland-protocols-1.15.tar.xz \
              && cd wayland-protocols-1.15 \
              && ./configure --prefix="/usr" --bindir="/usr/bin" --libdir="/usr/lib64" \
              && make install

          # libva
          RUN yum install -y \
              bzip2 \
              libdrm-devel \
              && cd /tmp \
              && curl -O -L --retry 5 \
              https://github.com/intel/libva/releases/download/2.10.0/libva-2.10.0.tar.bz2 \
              && tar xjf libva-2.10.0.tar.bz2 \
              && source /opt/rh/devtoolset-9/enable \
              && cd libva-2.10.0 \
              && ./configure --prefix="/usr" --enable-wayland --enable-x11 --bindir="/usr/bin" --libdir="/usr/lib64" \
              && make \
              && make install

          # install python 3.7.9
          RUN yum -y update \
              && yum install openssl-devel libffi-devel bzip2-devel -y \
              && yum install wget -y \
              && wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz \
              && tar xzf Python-3.7.9.tgz \
              && cd Python-3.7.9 \
              && ./configure --enable-optimizations \
              && make install

          # install pybind11
          RUN yum -y update && yum install wget -y \
              && cd /usr/local/src \
              && wget https://github.com/pybind/pybind11/archive/refs/tags/v2.6.2.tar.gz \
              && tar xzf v2.6.2.tar.gz \
              && cd pybind11-2.6.2 \
              && source /opt/rh/devtoolset-9/enable \
              && mkdir build \
              && cd build \
              && cmake .. \
              && make \
              && make install  

          # create devtoolset-9 entrypoint script since we can't source
          RUN echo "#!/bin/sh" > /etc/profile.d/entrypoint.sh \
              && echo ". /opt/rh/devtoolset-9/enable" >> /etc/profile.d/entrypoint.sh \
          # && echo "exec \"\$@\"" >> /tmp/entrypoint.sh \
              && chmod 755 /etc/profile.d/entrypoint.sh

          ENV BASH_ENV /etc/profile.d/entrypoint.sh

          # Enable dev tools when using this image
          #ENTRYPOINT ["/tmp/entrypoint.sh"]
          RUN groupadd -g \$GROUP_ID user || true
          RUN useradd --disabled-password --gecos "" --uid \$USER_ID --gid \$GROUP_ID user || true

          FROM maven:3-jdk-11 AS coverity_install
          SHELL ["/bin/bash", "-xo", "pipefail", "-c"]
          ARG COV_ANALYSIS_LINUX_URL
          ARG COV_REPORTS_LINUX_URL
          ARG COV_LICENSE_URL
          RUN mkdir /opt/coverity
          RUN curl --silent --show-error -o /tmp/cov-analysis-linux64.sh -k \${COV_ANALYSIS_LINUX_URL}
          RUN curl --silent --show-error -o /tmp/cov-reports-linux64.sh -k \${COV_REPORTS_LINUX_URL}
          RUN curl --silent --show-error -o /opt/coverity/license.dat -k \${COV_LICENSE_URL}
          run chmod 777 /tmp/*.sh
          RUN /tmp/cov-reports-linux64.sh -q \
                  --installation.dir=/opt/coverity/reports/
          RUN /tmp/cov-analysis-linux64.sh -q \
                  --installation.dir=/opt/coverity/analysis/ \
                  --license.agreement=agree --license.region=0 --license.type.choice=0 --license.cov.path=/opt/coverity/license.dat \
                  --component.sdk=false --component.skip.documentation=true
          
          FROM buildenv
          RUN yum install -y fontconfig
          ENV PATH="/opt/coverity/analysis/bin:/opt/coverity/reports/bin:\${PATH}"
          COPY --from=coverity_install /opt/coverity /opt/coverity

          EOL
          docker build -t vplcoverity:github_runner . \
            --build-arg http_proxy=$http_proxy \
            --build-arg https_proxy=$https_proxy \
            --build-arg no_proxy=$no_proxy \
            --build-arg "COV_ANALYSIS_LINUX_URL=${{ vars.COV_ANALYSIS_LINUX_URL }}" \
            --build-arg "COV_REPORTS_LINUX_URL=${{ vars.COV_REPORTS_LINUX_URL }}" \
            --build-arg "COV_LICENSE_URL=${{ vars.COV_LICENSE_URL }}"

      - name: Write Script (Linux)
        if: success() && runner.os == 'Linux'
        run: |
          cat > action.sh <<EOL
          #!/bin/bash
          set -o errexit ; set -o nounset
          set -x
          pushd source
          export VERBOSE=1
          cmake -B _build \
            -DCMAKE_INSTALL_LIBDIR=lib \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTS=OFF \
            -DENABLE_VA=ON \
            -DENABLE_DRM=ON \
            -DENABLE_WAYLAND=ON \
            -DENABLE_X11=ON \
            -DENABLE_DRI3=ON
          mkdir _reports
          REPORT_DIR="\$(realpath _reports)"
          BUILD_DIR="\$(realpath _build)"
          STRIP_DIR="\$(realpath .)"
          script/coverity-scan \
            --url "${{ vars.COVERITY_HOST}}" \
            --user "${{ vars.AD_USR }}" \
            --password "${{ secrets.AD_PW }}" \
            --email "${{ vars.AD_USR_EMAIL }}" \
            --stream "${{ vars.COVERITY_STREAM }}" \
            --project "${{ vars.COVERITY_PROJECT }}" \
            --project-name "oneVPL" \
            --dir "int_dir" \
            --report-dir "\${REPORT_DIR}" \
            --strip-path "\${STRIP_DIR}" \
            --code-version "${{ github.sha }}" \
            --bu "AXG" \
            --description "${{ github.ref_name }}" \
            ${{ inputs.COVERITY_OPTS}} \
            cmake --build "\${BUILD_DIR}" --parallel $(nproc) --verbose
          EOL
          chmod +x action.sh

      - name: Run Scan (Linux)
        if: success() && runner.os == 'Linux'
        run: |
          docker run --rm -v $PWD:/working -w/working vplcoverity:github_runner ./action.sh

      - name: Run Scan (Windows)
        if: success() && runner.os == 'Windows'
        run: |
          pushd source
          cmake -B _build
          if($LASTEXITCODE -ne 0)
          {
              Exit $LASTEXITCODE
          }
          mkdir _reports
          & script\coverity-scan.bat `
            --url "${{ vars.COVERITY_HOST }}" `
            --user "${{ vars.AD_USR }}" `
            --password "${{ secrets.AD_PW }}" `
            --email "${{ vars.AD_USR_EMAIL }}" `
            --stream "${{ vars.COVERITY_STREAM }}" `
            --project "${{ vars.COVERITY_PROJECT }}" `
            --project-name "oneVPL" `
            --dir "int_dir" `
            --report-dir "_reports" `
            --strip-path "." `
            --code-version "${{ github.sha }}" `
            --bu "AXG" `
            --description "${{ github.ref_name }}" `
            ${{ inputs.COVERITY_OPTS}} `
            cmake --build _build --parallel %NUMBER_OF_PROCESSORS% --verbose --config Release
          if($LASTEXITCODE -ne 0)
          {
            Exit $LASTEXITCODE
          }
          popd
            
      - name: Record Artifacts
        uses: actions/upload-artifact@v3
        if: (success() || failure())
        with:
          name: ${{ inputs.OS }}-coverity-scan
          path: source/_reports/*
  
      - name: Cleanup workspace (Linux)
        if: always() && runner.os == 'Linux'
        run: sudo rm -rf ..?* .[!.]* *

      - name: Cleanup workspace (Windows)
        if: always() && runner.os == 'Windows'
        run: Remove-Item -Recurse -Force .\*
