name: Release Summary
run-name: Release Summary (Triggered by ${{ github.event_name }} by @${{ github.actor }})
on:
  workflow_call:

jobs:
  summary:
    runs-on: [self-hosted, Linux, docker]
    steps:
      - name: Cleanup workspace (Linux)
        if: always() && runner.os == 'Linux'
        run: sudo rm -rf ..?* .[!.]* *
      - name: Create High Level Structure
        run: |
          mkdir -p summary
          mkdir -p summary/bom/linux
          mkdir -p summary/bom/windows
          mkdir -p summary/legal/ip_leaks
          mkdir -p summary/quality/acceptance/Linux/gen9.5
          mkdir -p summary/quality/acceptance/Linux/gen12.5
          mkdir -p summary/quality/acceptance/Windows/gen9.5
          mkdir -p summary/quality/acceptance/Windows/gen12.5
          mkdir -p summary/quality/operating_systems
          mkdir -p summary/quality/unit/Linux
          mkdir -p summary/quality/unit/Windows
          mkdir -p summary/security/CT7-KnownVulnerabilities
          mkdir -p summary/security/CT36-3rdPartyComponents
          mkdir -p summary/security/CT37-MalwareScan
          mkdir -p summary/security/CT39-StaticAnalysis
          mkdir -p summary/security/CT40-Custom
          mkdir -p summary/security/T256-CompilerSettings

      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
            path: artifacts
  
      - name: Copy and Rename Files
        run: |
          cp -r artifacts/ip-leak-scan/. summary/legal/ip_leaks/
          cp -r artifacts/linux-diff-report/. summary/bom/linux/
          cp -r artifacts/windows-diff-report/. summary/bom/windows/
          cp -r artifacts/windows-release-acceptance-gen12.5/. summary/quality/acceptance/Windows/gen12.5/
          cp -r artifacts/windows-release-acceptance-gen9.5/. summary/quality/acceptance/Windows/gen9.5/
          cp -r artifacts/linux-release-acceptance-gen12.5/. summary/quality/acceptance/Linux/gen12.5/
          cp -r artifacts/linux-release-acceptance-gen9.5/. summary/quality/acceptance/Linux/gen9.5/
          cp -r artifacts/windows-release-build-unit-tests/. summary/quality/unit/Windows/
          cp -r artifacts/linux-release-build-unit-tests/. summary/quality/unit/Linux/
          cp -r artifacts/windows-complier_settings/. summary/security/T256-CompilerSettings/
          cp -r artifacts/linux-complier_settings/. summary/security/T256-CompilerSettings/
          cp -r artifacts/distro-*/. summary/quality/operating_systems/
          cp -r artifacts/linux-release-build-dynamic-analysis/. summary/security/CT40-Custom/

          cp artifacts/linux-coverity-scan/json/errors_v9_full.json summary/security/CT39-StaticAnalysis/linux-coverity.json
          cp artifacts/windows-coverity-scan/json/errors_v9_full.json summary/security/CT39-StaticAnalysis/windows-coverity.json
          cp artifacts/vpl-vulnerability-scan/vulns.csv summary/security/CT7-KnownVulnerabilities/vulns.csv
          cp artifacts/vpl-vulnerability-scan/components.csv summary/security/CT36-3rdPartyComponents/components.csv
          cp artifacts/source-malware-scan/report.txt summary/security/CT37-MalwareScan/source-report.txt
          cp artifacts/windows-release-build-malware-scan/report.txt summary/security/CT37-MalwareScan/windows-build-report.txt
          cp artifacts/linux-release-build-malware-scan/report.txt summary/security/CT37-MalwareScan/linux-build-report.txt

      - name: Upload Summary
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: source-code-release-summary
          path: summary/*

      - name: Cleanup workspace (Linux)
        if: always() && runner.os == 'Linux'
        run: sudo rm -rf ..?* .[!.]* *
